# docker-compose.yaml
version: '3'

services:
  alice:
    build: '.'
    ports:
      - '5002:8000'
    environment:
      - OTHER_NAME=bob
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=alice
      - OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=sqlite3
  bob:
    build: '.'
    ports:
      - '5001:8000'
    environment:
      - OTHER_NAME=alice
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=bob
      - OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=sqlite3
